#!/usr/bin/env python3
"""Generate .NET consumer skill-route tables and the registry of routed repositories."""

from __future__ import annotations

import argparse
import json
import re
from pathlib import Path


CS_PATH = r"(?i:\.cs$)"
BUILD_PATH = r"(?i:(^|/)([^/]+\.(csproj|sln|slnx)|Directory\.(Build|Packages)\.props|Directory\.Build\.targets|global\.json|nuget\.config))$"
TEST_PATH = r"(?i:(^|/)tests?/|\.tests[./])"
TEST_PROJECT_CONTENT = r"(?i:<istestproject>\s*true|microsoft\.net\.test\.sdk)"
UNIT_TEST_PATH = r"(?i:(tests\.unit|unittests)[./])"
INTEGRATION_TEST_PATH = r"(?i:(tests\.integration|integrationtests)[./])"
E2E_TEST_PATH = r"(?i:(tests\.e2e|e2etests)[./]|\.feature$)"
DOMAIN_LAYER_PATH = r"(?i:\.domain/.*\.cs$)"
MODULE_LAYER_PATH = r"(?i:\.(application|infrastructure)/.*\.cs$)"
HTTP_EDGE_PATH = r"(?i:(controller|endpoint)s?\.cs$)"
DTO_PATH = r"(?i:\.contracts/.*\.cs$|(dto|request|response)s?\.cs$)"
REPOSITORY_PATH = r"(?i:(repository|repositories)\.cs$)"
PERSISTENCE_PATH = r"(?i:dbcontext\.cs$|(^|/)migrations/.*\.cs$)"
COMPOSITION_PATH = r"(?i:(^|/)program\.cs$|(servicecollection|dependencyinjection)[^/]*\.cs$)"
LOG_FILE_PATH = r"(?i:(^|/)log\.cs$)"
LOGGING_CONTENT = r"(?i:\bilogger\b|loggermessage)"
ERRORS_CONTENT = r"(?i:\bresult<|\bunitresult<|\boption<|\bierror\b)"
VALIDATOR_PATH = r"(?i:validators?\.cs$)"
MAPPER_PATH = r"(?i:mappers?\.cs$)"
SEEDING_PATH = r"(?i:seeders?\.cs$|(^|/)seeding/.*\.cs$)"
PROTO_PATH = r"(?i:\.proto$)"
KINDS = ("dotnet-service",)
REGISTRY = {
    "infonetica/cris-authz": "dotnet-service",
}
IDENTITY = re.compile(r"^[a-z0-9][a-z0-9._-]*/[a-z0-9][a-z0-9._-]*$")


def routes(kind: str) -> dict:
    if kind not in KINDS:
        raise ValueError(f"unknown kind: {kind}")
    rows = [
        {"path": r"^plans/", "skills": ["engineering:plans"]},
        {"path": r"^reviews/", "skills": ["engineering:review-lifecycle"]},
        {"path": r"(^|/)(AGENTS|CLAUDE)\.md$", "skills": ["engineering:docs-and-debt"]},
        {"path": r"(^|/)TECH_DEBT\.md$", "skills": ["engineering:docs-and-debt"]},
        {"path": CS_PATH, "skills": ["dotnet:style", "dotnet:naming"]},
        {"path": BUILD_PATH, "skills": ["dotnet:build", "dotnet:libraries", "dotnet:structure"]},
        {"path": TEST_PATH, "skills": ["dotnet:testing"]},
        {"path": r"(?i:\.csproj$)", "content_requires": TEST_PROJECT_CONTENT, "skills": ["dotnet:testing"]},
        {"path": UNIT_TEST_PATH, "skills": ["dotnet:testing-unit"]},
        {"path": INTEGRATION_TEST_PATH, "skills": ["dotnet:testing-integration"]},
        {"path": E2E_TEST_PATH, "skills": ["dotnet:testing-e2e"]},
        {"path": DOMAIN_LAYER_PATH, "skills": ["dotnet:domain-design"]},
        {"path": MODULE_LAYER_PATH, "skills": ["dotnet:structure-modules"]},
        {"path": HTTP_EDGE_PATH, "skills": ["dotnet:http-api"]},
        {"path": DTO_PATH, "skills": ["dotnet:naming-dtos"]},
        {"path": REPOSITORY_PATH, "skills": ["dotnet:persistence", "dotnet:naming-repositories"]},
        {"path": PERSISTENCE_PATH, "skills": ["dotnet:persistence"]},
        {"path": COMPOSITION_PATH, "skills": ["dotnet:dependency-injection"]},
        {"path": LOG_FILE_PATH, "skills": ["dotnet:logging"]},
        {"path": CS_PATH, "content_requires": LOGGING_CONTENT, "skills": ["dotnet:logging"]},
        {"path": CS_PATH, "content_requires": ERRORS_CONTENT, "skills": ["dotnet:errors"]},
        {"path": VALIDATOR_PATH, "skills": ["dotnet:validation"]},
        {"path": MAPPER_PATH, "skills": ["dotnet:naming-mapping"]},
        {"path": SEEDING_PATH, "skills": ["dotnet:seeding"]},
        {"path": PROTO_PATH, "skills": ["dotnet:proto"]},
    ]
    return {
        "_comment": [
            "Generated by tj-agents/dotnet dotnet:skill-routes gen_skill_routes.py; do not edit by hand.",
            "Architecture-keyed rows: every matching route fires, and the .cs floor always applies.",
        ],
        "kind": kind,
        "layers": ["engineering", "dotnet"],
        "routes": rows,
    }


def registry_document() -> dict:
    for identity, kind in REGISTRY.items():
        if not IDENTITY.match(identity):
            raise ValueError(f"registry identity must be a lowercase owner/name: {identity}")
        if kind not in KINDS:
            raise ValueError(f"{identity} is registered for an unknown kind: {kind}")
    return {
        "_comment": [
            "Generated by tj-agents/dotnet dotnet:skill-routes gen_skill_routes.py; do not edit by hand.",
            "skill_router.py reads this only when shipped beside it as routes/registry.json; a repo-committed .agents/skill-routes.json always wins.",
        ],
        "repos": dict(sorted(REGISTRY.items())),
    }


def rendered(document: dict) -> str:
    return json.dumps(document, indent=2, ensure_ascii=False) + "\n"


def emitted_files(directory: Path) -> dict[Path, str]:
    files = {directory / "registry.json": rendered(registry_document())}
    for kind in sorted(set(REGISTRY.values())):
        files[directory / f"{kind}.json"] = rendered(routes(kind))
    return files


def skills_for(kind: str, path: str, content: str = "") -> set[str]:
    matched: set[str] = set()
    for route in routes(kind)["routes"]:
        if not re.search(route["path"], path):
            continue
        needle = route.get("content_requires")
        if needle and not re.search(needle, content):
            continue
        matched.update(route.get("skills") or [])
    return matched


def write_or_check(files: dict[Path, str], check: bool) -> int:
    stale = False
    for target, expected in files.items():
        if check:
            actual = target.read_text(encoding="utf-8") if target.is_file() else None
            if actual != expected:
                print(f"STALE: {target}")
                stale = True
            else:
                print(f"current: {target}")
        else:
            target.parent.mkdir(parents=True, exist_ok=True)
            target.write_text(expected, encoding="utf-8", newline="\n")
            print(f"generated: {target}")
    return 1 if stale else 0


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--kind", choices=KINDS)
    parser.add_argument("--into", type=Path)
    parser.add_argument("--emit-registry", type=Path)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    if args.emit_registry and (args.kind or args.into):
        parser.error("--emit-registry cannot be combined with --kind/--into")
    if args.emit_registry:
        return write_or_check(emitted_files(args.emit_registry.resolve()), args.check)
    if not args.kind or not args.into:
        parser.error("--kind and --into are required without --emit-registry")
    target = args.into.resolve() / ".agents" / "skill-routes.json"
    return write_or_check({target: rendered(routes(args.kind))}, args.check)


if __name__ == "__main__":
    raise SystemExit(main())
